- README.md
I think this is a new course. I'm enrolled in the current session.
> Adding course

- README.md
Add inspiring video by Andrew Ng talking about deep learning.
> Add inspiring video by Andrew Ng

- README.md
Reverts ZuzooVn/machine-learning-for-software-engineers#5
> Revert "grammar errors"

- README-portuguese.md
- README-pt-BR.md
I wanted to do this translation of this repository to Brazilian Portuguese, because I think it will help brazilians anyway.
> Translation to Brazilian Portuguese

- README.md
Hello! I contributed a few relevant resources from Data School. If you have any questions, please let me know and I'm happy to answer them!
> Add resources from Data School

- README.md
* Changed tabs to spaces for consistency in alignment
* Added a space to a header to make it consistent with others
* Modified a couple of sentences for flow
> Minor formatting, grammar and sentence-flow changes

- README.md
There are many resources (videos, lecture notes, problem sets ...) provided by many courses in Universities like Stanford, Cambridge or Oxford that can be useful to explore
> Add machine learning courses in many universities

- README-zh-CN.md
> Translation to Chinese

- README.md
- collection of resources for developers who want to get started with
machine learning.
> adding Intro to Machine Learning for Developers

- README-pt-BR.md
Beacuse great projects need to be shared!
> Add share on Twitter link for PT-BR

- README.md
added DeepLearning.TV video series
> added DeepLearning.TV video series

- README.md
removed Statistics repetition.
> Fixed Typing Error

- README.md
http://martin.zinkevich.org/rules_of_ml/rules_of_ml.pdf
> Added best practices rule book for ML from Google

- README.md
Hello,
Thanks for including my article series in your repo! It's greatly appreciated!
I've changed the article series title a while ago, and am submitting this pull request to update in your repo if possible.
Thanks again!
Alex
> Update article series title to current

- README.md
I added this article because it contains a lot of excellent materials for whom are looking for a way to start with Machine Learning: Introduction, choose a programming language to start, basic maths knowledge, libraries, cheatsheet and some examples for them to build. It's short and concise.
I think it's a great resource, not only for beginners but also who is already familiar with Machine Learning
> Add "Absolute Beginning into Machine Learning"

- README-zh-CN.md
- README.md
The link of [121 Essential Machine Learning Questions & Answers] is not valid any more. 
I have updated the new url to both files for English and Chinese version.
> update link 

- README.md
https://hackr.io/tutorials/learn-machine-learning-ml
> Added Curated ML Resources

- README.md
Added two repositories with ML research papers and their implementations.
> Added 2 ML research paper aggregator repositores.

- README.md
Hi,
I am Branko and I work with Manning Publications.
I thought this Manning book might be a good title for your list.
Thanks for considering it!
> Added Succeeding with AI

- README.md
Hello,
Thanks a lot for maintain this resources repo. I thought that my new book would be a valuable addition to your list of Practical Books.
I did not add it to the other languages version of the list, as I saw that sometimes the titles get translated to the other language. But if you wish to add it to the other lists, I'd be happy to do so.
Thanks for your consideration.
> Add how machine learning works to practical books

- README.md
I only made a slight grammatical improvement in the Prerequisite Knowledge section of the README file.
> Grammatical Improvement

- README.md
Added a link to podcasts on YouTube on interviews with leading researchers in the ML community.
And a link to the audio podcasts.
> adding ml for beginners podcast

- README.md
How to Become a Machine Learning Engineer: Added the How to Become a Machine Learning Engineer blog to the Machine Learning Overview section, providing a structured learning path to the machine learning aspirants.
If you find the resource useful, please merge this and let me know in case of any further changes.
Thank you
> Added one new resource
